import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { Banner } from '../components/banner'
import { HomeHeader } from '../components/home/homeHeader'

const Home: NextPage = () => {
  // use any click to look for the target
  // if it is the text input, animate Betty to look down
  // if it is the submit button, animate Betty to CHOMP
  // eslint-disable-next-line
  const onPageClick = (e: any) => {
    console.log('page click target is: ', e?.currentTarget)
  }
  return (
    <div onClick={onPageClick} className={styles.container}>
      <Head>
        <title>Mazmatics fun math 4 kids</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* this could be it's own componentn */}
        <HomeHeader />
        <div className={styles.product_book1}>
          <h2 className={styles.product_book1__heading}>
            <Banner
              className={styles.homeBanner1}
              title="Fun Math 4 kids play-book"
              size="small"
              color="yellow"
            />
          </h2>
          <p className={styles.product_book1__subtitle}>out soon as!</p>
        </div>
        <div className={styles.pointer}></div>
        {/* // own component */}
        <div className={styles.signup}>
          <div className="ml-embedded" data-form="ltd6tR"></div>
        </div>

        <div className={styles.waves}>
          <svg
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
          >
            <path
              d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z"
              className="shape-fill"
            ></path>
          </svg>
        </div>

        <Banner
          className={styles.homeBanner2}
          title="Fun Math 4 kids book"
          subtitle="Volume 1 – coming soon"
          size="med"
          color="purple"
        />
      </main>
    </div>
  )
}

export default Home
